server:
  port: 8082
spring:
  application:
    name: customerProduct-service
  config:
    import:
      - optional:configserver:https://ms-config.azurewebsites.net
  data:
    mongodb:
      uri: mongodb+srv://admin:5K8yj70q4RpuiBSE@bootcamp37.anglhbu.mongodb.net/db_customerProduct
eureka:
  client:
    service-url:
      defaultZone: https://ms-discovery.azurewebsites.net/eureka/
management:
  endpoint:
    web:
      exposure:
        include: "*"
message:
  path-customerProductActives: /api/v1/customerActivesProducts
  path-customerProductPassives: /api/v1/customerPassivesProducts
  path-customerDomain: https://ms-customer-bc37.azurewebsites.net
  path-customerResponse: /api/v1/customers/
  path-productDomain: https://ms-product-bc37.azurewebsites.net
  path-productResponse: /api/v1/products/
resilience4j:
  circuitbreaker:
    instances:
      ms-customer:
        register-health-indicator: true
        event-consumer-buffer-size: 20
        failure-rate-threshold: 50
        minimumNumberOfCalls: 10
        automatic-transition-from-open-to-half-open-enabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 6
        slidingWindowSize: 20
        slidingWindowType: COUNT_BASED